version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmarkAPI
    networks:
      - bookmarkAPI
    volumes:
      - bookmarkAPI-data:/var/lib/postgresql/data
networks:
  bookmarkAPI:
volumes:
 bookmarkAPI-data: